### ISSUE TITLE
Help in ErrorException in Translator.php line 95

### ISSUE THREAD

**Issue by ClaudioVarandas** [vsch/laravel-translation-manager#10]
ErrorException in Translator.php line 95:
Trying to get property of non-object (View: -----/resources/views/vendor/laravel-translation-manager/index.blade.php)

Any ideias ? im getting this error when i click in inline or select many locales that dont exists in file system.

Thank you

CV

**Comment by vsch** [comment]
@kadinho thanks for reporting this. It is a bug that has an easy work around.

In the translation manager configuration enable `log_missing_keys`.

``` php
    /**
     * determines whether missing keys are logged
     *
     * @type boolean
     */
    'log_missing_keys' => true,
```

I will be releasing a new version soon with this bug fixed.

You can patch the `src/Manager.php` file, function `missingKey`.  Change [this line](https://github.com/vsch/laravel-translation-manager/blob/2.0.28/src/Manager.php#L230) which tests for this setting, to test true if 'log_missing_keys' setting is enabled or if parameter `$useLottery` is false.

``` php
        if (!in_array($group, $this->config()['exclude_groups']) && $this->config()['log_missing_keys'])
```

change to:

``` php
        if (!in_array($group, $this->config()['exclude_groups']) && (!$useLottery || $this->config()['log_missing_keys']))
```

In place edit mode uses the missingKey() function because it needs a real translation in all cases and since I always have this mode enabled, I never came across this bug.

**Comment by ClaudioVarandas** [comment]
Works! thx :)
