### ISSUE TITLE
JSON Translation files

### ISSUE THREAD

**Issue by tiagofcp** [vsch/laravel-translation-manager#104]
Hi 
is this compatible with json translations files and with __("") on laravel 5.4 already?

Thanks

**Comment by vsch** [comment]
@tiagofcp, no. JSON translations are not supported. If someone wants to add this functionality I would definitely welcome it but I am at the moment too short on time to implement this change.

**Comment by vsch** [comment]
@tiagofcp, Versions 2.6.4, 2.5.6 and 2.4.36 for Laravel 5.6, 5.5 and 5.4 respectively, have been released with JSON translation file support. [Versioninfo.md](https://github.com/vsch/laravel-translation-manager/blob/master/versioninfo.md#264)

**Comment by tiagofcp** [comment]
Hi i just saw that LTM is supporting JSON translation files, but im having issues, it can load all the translations but not the ones on the en.json, its only loading the json files.
Do i need to configure something?
Thanks for this improvement, i really like this tool

**Comment by vsch** [comment]
@tiagofcp, you should not need to configure anything unless you want to tweak default json configuration settings. That said you may want to copy json related config entries to your ltm config file, in case a bug is causing an issue.

The JSON files are expected to be in the resources/lang directory and have locale name with `.json` extension.

When they are imported they are put into the `JSON` group since these translations do not have a group.

On export the translations will be put into locale.json files in the resources/lang directory.

There is also a json.json file created in the same directory to preserve LTM database translation key mapping since json language files use the primary locales text as the key which is not compatible with LTM implementation.

Because of this dependency when you import/export JSON translations you should have the primary locale set correctly. It should not affect the operation but I have not tested for this scenario.

If you already imported with the wrong primary locale, just delete the `JSON` group in LTM and re-import.

**Comment by tiagofcp** [comment]
JSON group does not appear to me on the groups after i import. and the locale.json files are in ressources/lang include the primary one en.lang

I will try to test with another project to see if the same happens

**Comment by vsch** [comment]
@tiagofcp, forgot to mention that this was added to branch 2.5 which is Laravel 5.5 compatible. If you are using previous versions then this functionality is not available.

**Comment by tiagofcp** [comment]
@vsch im using Laravel Framework 5.6.38, im now trying with this demo project that is laravel 5.5 
https://github.com/bestmomo/laravel5-5-example

**Comment by tiagofcp** [comment]
with that demo i was able to load the json, so its needs to be something wrong with the laravel 5.6 or our app, i will further check this

**Comment by tiagofcp** [comment]
does LTM detects strings to translate on the blades that use this __("something") instead of the @lang("something") ??

**Comment by vsch** [comment]
@tiagofcp, LTM Translator implementation also intercepts __() translations.

What do you mean by detect? Translation is handled by Laravel. LTM is not involved in blade processing.

**Comment by tiagofcp** [comment]
ok, i was tryiing to find the issue, but it must be something on our project, i will try to setup a new project with the same laravel version to test
