### ISSUE TITLE
How to add extra/custom locales ?

### ISSUE THREAD

**Issue by ClaudioVarandas** [vsch/laravel-translation-manager#11]
Hello,

Nice pkg btw !

How can i define extra locales for translatation ? and how to add new locales for translation ?

Many thx
CV

**Comment by kadinho** [comment]
Im gonna extend the controller for now with a extra locales array from the config. But it could be a nice feature :)

**Comment by ClaudioVarandas** [comment]
For now im testing with the following workaround:

```
protected
function loadLocales()
{
    //Set the default locale as the first one.
    $currentLocale = Config::get('app.locale');
    $primaryLocale = $this->primaryLocale;
    $translatingLocale = Cookie::get($this->cookieName(self::COOKIE_TRANS_LOCALE), $currentLocale);

    //WORKAROUND START
    //$locales = Translation::groupBy('locale')->lists('locale')->all() ?: [];
    $locales = config('laravel-translation-manager.locales');
    //WORKAROUND END
    $locales = array_merge(array($primaryLocale, $translatingLocale, $currentLocale), $locales);
    return array_flatten(array_unique($locales));
}
```

**Comment by vsch** [comment]
@kadinho, you are welcome. I think it is a little discovered productivity bomb-shell. I can't work without it and now all websites in Php that I create, even ones that are one language only, I use this package and remove any hard-coded text. It is so much easier to maintain a site when all the text can be easily modified without having to search through views. I also have the in-place-edit setup for all pages so that I can make corrections or just identify which translation group-key is used for a piece of text on the page.

### To add new locales

All you need to do is add a single locale file in your lang directory with a single translation. Do that for every locale that you want to add. Then do an **Import** with just **Only add new translations** 
<img width="373" alt="screen shot 2015-10-05 at 1 22 29 pm" src="https://cloud.githubusercontent.com/assets/10299086/10287990/3430ea04-6b64-11e5-895c-9cbc49b74694.png">
and the locale(s) will be in the list. Since it is only done when you setup a new locale, it was not a high-priority feature to add. I will add this and `Create new group` to the todo list. Both have the same workaround. Create any group file for the locale, or create a specific file for the group in any locale, with a single translation key, even one with a blank translation.

You can just create a dummy translation file and copy it to all locales that you want to create. If you are using [PhpStorm](https://www.jetbrains.com/phpstorm) (if you are not then you should be) then you can create a file template `Php Translation File` then you can create the locale directories and do a <kbd>New > Php Translation File</kbd> to create a new file with a dummy translation already there.

add this to its template body:

``` php
<?php
#parse("PHP File Header.php")

return array(

    /*
    |--------------------------------------------------------------------------
    | ${FILE_NAME}
    |--------------------------------------------------------------------------
    |
    | The following language lines are used by the website to ??? localized ???
    |
    */
    'translation-key' => 'translation',
);

```

so that all new translation files will start off with this content:

``` php
<?php
/**
 * Created by PhpStorm.
 * User: vlad
 * Date: 2015-10-05
 * Time: 1:03 PM
 */
return array(

    /*
    |--------------------------------------------------------------------------
    | 
    |--------------------------------------------------------------------------
    |
    | The following language lines are used by the website to ??? localized ???
    |
    */
    'translation-key' => 'translation',
);

```

Here is the PhpStorm file and code template config settings page view:

<img width="1240" alt="screen shot 2015-10-05 at 1 10 20 pm" src="https://cloud.githubusercontent.com/assets/10299086/10287672/7ee5415a-6b62-11e5-878b-274bb5ed85cf.png">

**Comment by vsch** [comment]
@kadinho, you should not have any vendor packages included by default. To include them you need to change the config file.

I would not override the locales from the database. Then you will need to edit the config file every time to add a locale. I would instead add the config locales to the ones from the database so that they show up even if they don't exist in the translation files or database:

``` php
protected
function loadLocales()
{
    //Set the default locale as the first one.
    $currentLocale = Config::get('app.locale');
    $primaryLocale = $this->primaryLocale;
    $translatingLocale = Cookie::get($this->cookieName(self::COOKIE_TRANS_LOCALE), $currentLocale);

    $locales = Translation::groupBy('locale')->lists('locale')->all() ?: [];
    //WORKAROUND START
    $configLocales = config('laravel-translation-manager.locales');
    //$locales = array_merge(array($primaryLocale, $translatingLocale, $currentLocale), $locales);
    $locales = array_merge(array($primaryLocale, $translatingLocale, $currentLocale), $configLocales, $locales);
    //WORKAROUND END
    return array_flatten(array_unique($locales));
}
```

**Comment by ClaudioVarandas** [comment]
yes, it's a better approach :) can be added in the next version ?  

Thank you 
CV

**Comment by vsch** [comment]
Already in the code. So it will be in the next release. 

You can add it to yours, here is the final version. It uses standard functions in manager that differ between Version 4.2 and 5.1.

in Controller.php:

``` php
    protected
    function loadLocales()
    {
        //Set the default locale as the first one.
        $currentLocale = \Config::get('app.locale');
        $primaryLocale = $this->primaryLocale;
        $translatingLocale = \Cookie::get($this->cookieName(self::COOKIE_TRANS_LOCALE), $currentLocale);

        $locales = $this->getTranslation()->groupBy('locale')->lists('locale')->all() ?: [];

        $configLocales = $this->manager->config('locales', []);
        if (!is_array($configLocales)) $configLocales = array($configLocales);

        $locales = array_merge(array($primaryLocale, $translatingLocale, $currentLocale), $configLocales, $locales);
        return array_flatten(array_unique($locales));
    }

```

**Comment by ClaudioVarandas** [comment]
Cool

**Comment by vsch** [comment]
New translation manager for Laravel 5.1 is available.
