### ISSUE TITLE
Json: Wrong import e.g. "[last] dddd": "[letzten] dddd" becomes to "-last-dddd" as key

### ISSUE THREAD

**Issue by pmochine** [vsch/laravel-translation-manager#149]
See my title example

**Comment by pmochine** [comment]
The problem what I see is, that it ignores every key how I set it it writes it in small caps with -

`"Are you sure you want to delete it?": "Bist du dir sicher, dass du es löschen willst?",`

becomes to `are-you-sure-you-want-to-delete-i`

The "english" part of json goes complety away with that

**Comment by vsch** [comment]
@pmochine, I have not tested the React UI with Laravel 6.0. That was the reason I did not merge the 6.0 changes into master.

Does it work without the React UI? 

JSON translations a PITA because LTM expects keys to be limited to something that can be passed on the URL and processed by JavaScript without escaping. JSON translations break that.

LTM for JSON translations generates keys to use in the database and UI. It keeps these in the json.json translation files if memory serves correctly. These files must be kept as part of the JSON translation files so that the converted keys could be mapped back to actual keys used in the JSON translation files. All this is from memory of code I have not looked at for over a year. So I might loose a bit of accuracy in the details.

Your original JSON keys will appear under the primary language column. There is no way to make LTM work with JSON keys because these can be anything of any length. So creating dummy keys and using the original as primary translation. If you change the primary keys in LTM the saved JSON will still have original keys but now the changed ones will have new values for the primary locale file.

I wold suggest trying the Web UI first and making sure things work with 6.0. After that I would look at why React UI is failing on 6.0.

**Comment by pmochine** [comment]
Thank you for your fast answer! I appreciate it. Weird that it works perfectly with barryvdh package.  Nonetheless; I have a workaround for my problem. Thanks for your awesome package!

**Comment by vsch** [comment]
@pmochine, LTM has diverged from barryvdh long ago. I have not worked on LTM in over a year so there are probably changes needed for Laravel 6 but at the moment I have no time to spend on it.
