### ISSUE TITLE
No publishhable Resources (and other bugs)

### ISSUE THREAD

**Issue by syntafin** [vsch/laravel-translation-manager#153]
I tried to install this package as it is decribed. When I try to publish Migrations, Config, Public etc Artisan throw the following error (for all!):

`PS E:\Projekt Daten\LaraMinefield> php artisan vendor:publish --provider="Vsch\TranslationManager\ManagerServiceProvider" --tag=migrations
Unable to locate publishable resources.
Publishing complete.`

If you still try afterwards to start the application:
`PS E:\Projekt Daten\LaraMinefield> php artisan serve

   ErrorException  : array_key_exists() expects parameter 2 to be array, null given

  at E:\Projekt Daten\LaraMinefield\vendor\vsch\laravel-translation-manager\src\Translator.php:757
    753|     {
    754|         $config = App::get('config')[\Vsch\TranslationManager\ManagerServiceProvider::PACKAGE];
    755|         $key = \Vsch\TranslationManager\Manager::DISABLE_REACT_UI;
    756| 
  > 757|         $disableReactUI = array_key_exists($key, $config) ? $config[$key] : false;
    758|         Controller::routes($disableReactUI);
    759|     }
    760| 
    761|     public static function webRoutes()

  Exception trace:

  1   array_key_exists("disable-react-ui")
      E:\Projekt Daten\LaraMinefield\vendor\vsch\laravel-translation-manager\src\Translator.php:757

  2   Vsch\TranslationManager\Translator::routes()
      E:\Projekt Daten\LaraMinefield\routes\web.php:32

  Please use the argument -v to see more details.`

Laravel 6.10

**Comment by vsch** [comment]
@syntafin, the package is not updated for Laravel 6.10 and since Laravel usually has breaking changes between releases, I suspect this is the case here.

I don't know when I will be able to make it Laravel 6.1 compatible since I don't work in Laravel nor PHP and will have to come up to speed with what has changed in 6.1 that is breaking the package.

The last Laravel upgrade which I worked on was 5.6, the rest were user contributions. I am too swamped lately to be able to maintain this package.

**Comment by syntafin** [comment]
That is just sad :(. I am looking for a TM-Package because the translation team should not translate it right in the App code.

**Comment by vsch** [comment]
@syntafin, I agree. I hate abandoning projects but being human I only have so many hours in a day and must use at least 6 of them for sleep.

I do not see having more time in the future since I do not work in Php nor Laravel any more. Maintain a project which I no longer use is very difficult to justify from time management perspective.

I would hope that someone will pick up where I left off. There are many improvements to be made.

As I say on my site, "Like a poem, no software is ever finished. It is merely abandoned."

**Comment by syntafin** [comment]
I decided to port it for Laravel 6.10 :) will see if I use your's or barryvd's Version as base!

**Comment by vsch** [comment]
@syntafin, the two are different beasts altogether. The one you choose should depend on the features you need. The two projects diverged almost immediately after I forked his project because I needed to add all the auto translation and other creature comforts. Once others started using it the feature list grew with user requests.

I don't think it should be a big deal to update it for 6.1. Just have to see what Laravel 6.1 broke with respect to their API from 6.0.
