### ISSUE TITLE
Find function isn't supported in Laravel 5

### ISSUE THREAD

**Issue by karlisabele** [vsch/laravel-translation-manager#22]
The <pre><code>php artisan translations:find</code></pre> is not supported in Laravel 5, because the function is looking into app directory, but the view files are in resources/views directory.

**Comment by vsch** [comment]
@karlisabe, thank you for the heads up. it can be changed to look in the right place but I don't know if it is worth doing it. I ran it once when I first forked the project and it was more trouble than it was worth trying to clean up all the irrelevant stuff it created in the translation table. it was easier to delete all and import from scratch.

I will probably remove it and if I ever get a chance to improve its false positives then I will put it back.

That was the reason I improved the logging of missing keys so it can be run in production, so that anything that is missed by running it in development will at least be flagged in prod.

Anytime I create code I don't even bother creating translations, even for English. I just run the code and with the page open, I then go into translation manager and edit the empty keys, publish, then return and refresh the page to see what it looks like. Much easier that way. If I am pressed for time I don't enter the English version, just do auto-fill and continue development.

Once I am done, I go back and think of better labels and strings, but for development what auto-fill provides is good enough.

**Comment by karlisabele** [comment]
@vsch 
Thanks for the advice on the workflow :)

**Comment by vsch** [comment]
@karlisabe, translate:find fixed. Also added source references to translations. So now you can see where in the source the translation group.key is being used.

Latest update requires migration publishing from the package and running migrations.

![screenshot_showrefsicons](https://cloud.githubusercontent.com/assets/10299086/15376437/fa9b1ab4-1d22-11e6-8a5f-42a5c7ac7b75.png)

![screenshot_showsourcerefs](https://cloud.githubusercontent.com/assets/10299086/15376438/fa9e4f86-1d22-11e6-8214-0a94563364d7.png)
