### ISSUE TITLE
switch from barryvdh to your package

### ISSUE THREAD

**Issue by UnrulyNatives** [vsch/laravel-translation-manager#27]
I just installed your package as it seems to approach the issue of access by several users, each responsible for their own language.

I have this problem: 
I made over 2000 translations to 5 languages which are stored in `ltm_translations`.

Is there any tested way to migrate from barryvdh package into yours?

**Comment by vsch** [comment]
@UnrulyNatives, I never tried migrating from the package but it was developed from barryvdh package.

I don't see why it would not work. The migrations in my package include the original migration that creates the table. All other changes are implemented in addition to this script.

To be on the safe side publish all your translations using barryvdh package so that they are preserved in translation files. In the worst case you can import all translations from these files.

BTW,  per user access control is not yet implemented but is the next item on the to do list.

**Comment by UnrulyNatives** [comment]
Hi, sorry to bother you. 
I already lost a some time struggling to migrate my translations to your package.
It might be because I have the translations table in a secondary database.

In act of desperation I manually added columns to the table...
but then another problem appeared:
`SQLSTATE[21000]: Cardinality violation: 1222 The used SELECT statements have a different number of columns (SQL: SELECT * FROM common_database.ltm_translations WHERE`group`= AND locale IN ('en','pl','de','es','zw-tw','en','pl')`

Possible solution: maybe name of your translations table should be different than the barryvdh's `ltm_translations`.

**Comment by vsch** [comment]
@UnrulyNatives, not a problem.

The table by default is ltm_translations. From the error it appears that there is a UNION and the select statements have different number of columns.

I would guess that you modified some of the selects for the new table but missed others.

I will be adding a configuration item to specify the database name to be used for the translation tables.

**Comment by vsch** [comment]
@UnrulyNatives, did you try changing the $table in Translation model to 'common_database.ltm_translations'

This setting is used by all the SQL queries. So the generated SQL will have the database name prefixed to the table.

**Comment by vsch** [comment]
@UnrulyNatives forgot to add the link: https://github.com/vsch/laravel-translation-manager/blob/master/src/Models/Translation.php#L25 to the file

**Comment by vsch** [comment]
@UnrulyNatives see #28.
