### ISSUE TITLE
Closure in config file breaks config:cache

### ISSUE THREAD

**Issue by Casinelli** [vsch/laravel-translation-manager#29]
The commit https://github.com/vsch/laravel-translation-manager/commit/d690a98e951cec0caf6a3062565996783a508702 adds a closure in the configuration file. Specifically:

```
'user_list_provider' => function ($user, $connection_name) {
    /* @var $connection_name string */
    /* @var $user  Illuminate\Database\Eloquent\Model */
    /* @var $query  Illuminate\Database\Eloquent\Builder */
    $query = $user->on($connection_name);
    return $query->orderby('id')->get(['id', 'email']);
},
```

Unfortunately that breaks artisan's config:cache command. Taylor Otwell has stated multiple times that they're not going to support this as the time cost of unserializing closures is too high and would defy the point of speed improvement through caching.

**Comment by vsch** [comment]
@Casinelli, I will replace the user privilege manager and use the Gate ability/policy mechanism that will provide all user access functions, including providing a user locale list. 

I have wanted to remove the dependency on user privilege manager which was only needed for Laravel 4 since Laravel 5 has a much cleaner Gate service and policies mechanism.

Translation Manager abilities would all start with 'ltm-' to avoid conflicts.
- `ltm-admin-translations` true/false whether the user can administer translations
- `ltm-bypass-lottery` true/false whether the user is subject to missing key translation lottery
- `ltm-editors` would return an array of users with id, email and optional name.

I will change the minor version since this is not a backwards compatible method. I will also remove the user list provider closure from config.

What do you think of this approach?

**Comment by vsch** [comment]
@Casinelli, I forgot to add that these would be implemented in `LtmPolicy`, with default implementation provided by the LTM package.

**Comment by vsch** [comment]
@Casinelli version 2.1.0 released. This version is upgraded to Laravel 5.2 and uses abilities for all LTM authorizations. Dependency on `UserPrivilegeMapper` was removed. 

Need to change composer dependency to: "vsch/laravel-translation-manager": "~2.1"
