### ISSUE TITLE
translations:import is not working

### ISSUE THREAD

**Issue by itviventura** [vsch/laravel-translation-manager#31]
Hi @vsch,

First of all I would like to thanks you for this great service It is so useful for my project, I have installed it  including all settings explained in documentation I have created translation groups correctly http://screencast.com/t/hOkY0YyR however when I run translations:import I got always the same message "Done importing, processed 0 items" so http://screencast.com/t/CgPigBklil

Do you know what's going on there?

Thanks a lot for your help.

**Comment by vsch** [comment]
@itviventura, it seems not to find your translation files. 

The file import loop is in: https://github.com/vsch/laravel-translation-manager/blob/master/src/Manager.php#L889-L896

Can you see if the `$langFiles` contains the list of files? I suspect that there is something in the configuration which is causing it not to find the language resource files.

The default configuration expects the resource files to be at the root of the application, as returned by `$app->basePath()`

If you changed the `'language_dirs'` setting in configuration, can you put it back to the default and see if it solves the issue. This setting is very quirky.

If the `$langFiles` above is empty then the issue is a few lines above: https://github.com/vsch/laravel-translation-manager/blob/master/src/Manager.php#L868-L872

**Comment by itviventura** [comment]
Hi @vsch,

The base path is right so http://screencast.com/t/izagjgUIkMg even for language_dirs I didn't do any change there as you said me the problem is here https://github.com/vsch/laravel-translation-manager/blob/master/src/Manager.php#L868-L872 because $langFiles array is empty.

What could I do in order to know why $langFiles is empty?

Thanks.

**Comment by vsch** [comment]
@itviventura, the loading of the file list is done here: https://github.com/vsch/laravel-translation-manager/blob/master/src/Classes/PathTemplateResolver.php#L265-L287

If you set a break point and examine $this->config_paths like here:

<img width="594" alt="screen shot 2016-05-10 at 10 51 40 pm" src="https://cloud.githubusercontent.com/assets/10299086/15168710/e1a9e4f8-1701-11e6-8d85-35d819a3e417.png">

You should see all the possible location templates where it will try to find translation files. The important one is the standard location `/resources/lang/{locale}/{group}`:

<img width="662" alt="screen shot 2016-05-10 at 10 46 34 pm" src="https://cloud.githubusercontent.com/assets/10299086/15168721/fa8bb190-1701-11e6-8976-5ee0316b5f73.png">

On the second step through the loop it loads files for this entry, after the call to `$this->loadFileList()` on line 283, `$this->lang_files` should contain the list of language files with a full path on your system. Something like:

<img width="634" alt="screen shot 2016-05-10 at 10 58 27 pm" src="https://cloud.githubusercontent.com/assets/10299086/15168800/c073ab10-1702-11e6-9de2-ab8f0e45ec79.png">

If it does not then there is a problem somewhere in the configuration and it will take more digging.

**Comment by vsch** [comment]
fixed. Caused by Windows path separator not being recognized in processing of language directories.
