### ISSUE TITLE
Typo in documentation and ,missing require ?

### ISSUE THREAD

**Issue by yurtesen** [vsch/laravel-translation-manager#35]
Thanks for fixing the symphony/finder versions earlier in composer. Today I decided to install the translation manager and hit some new problems.

1- First of all the installation manual says:https://github.com/vsch/laravel-translation-manager/wiki/Installation

> ```
> if you are not going to be customizing the web interface it is highly recommended that you add automatic asset publishing for this package after upgrade in your project's composer.json:
> ```

Does it mean 'if you ARE going to' ? It sounds like that 'not' is extra there?

2- I realized that the ltm needs "laravelcollective/html" but this is neither installed by laravel itself nor by the ltm. Should it be added to composer config?

**Comment by vsch** [comment]
@yurtesen "If you are not going to be customizing...." means that if you are going to use the WebUI as is then you should add this line to the post-update-cmd. That way every time some of the stylesheets or JavaScript files change in the package, you will get the update. Most people should add this line because many updates are made to the stylesheets and js files in the package.

There is a dependency on laravelcollective/html in the ltm composer require section and steps 2 and 3 of installation give instructions on adding the needed service and façades

``` json
    "require": {
        "php": ">=5.5.9",
        "illuminate/support": "~5.2",
        "illuminate/translation": "~5.2",
        "doctrine/dbal": "~2.3",
        "laravelcollective/html": "~5.2",
        "symfony/finder": "3.0.*"
    },
```

Are you using the old Laravel 4.2 version of LTM? Because that old version did not need laravelcollective/html because it was part of laravel.

**Comment by yurtesen** [comment]
Ah, I thought the text was talking about the web interface of my site :) and I thought "well I will customize it obviously" lol

It is strange, because for some reason I didn't have "laravelcollective/html" then had to install it manually. So automatically I thought it wasnt in composer.json

Now I tried to remove everything and install LTM and it installed the "laravelcollective/html". I don't know what happened. But apparently my mistake :) Sorry to bother...

**Comment by vsch** [comment]
@yurtesen, not a problem. Let me know if you encounter other issues.
