### ISSUE TITLE
Inline translations break page layouts

### ISSUE THREAD

**Issue by yurtesen** [vsch/laravel-translation-manager#38]
I am no HTML expert, but the way the inline translations work feels wrong. Also cumbersome to code inside the templates. Also I may be wrong but this is what I think may be a good solution:

I think there should be a single function in form of

`inlineEditorHelper('<a href="blah">{{ trans('keyname') }}</a>','keyname')`

This function would return result of normal translation if inline editing is disabled:

`<a href="blah">{{ trans('keyname') }}</a>`

If inline editing is enabled, it would return something like this:

`<span style="position:relative;" onmouseover="show popup with id" onmouseout="hide popup with id"><a href="blah">{{ trans('keyname') }}</a><span><a style="position:absolute; display: none;"....then the usual stuff>$diff</a>`

This way, when one comes on top of the text to be translated, the translation link would pop up without breaking the page layout.

An alternative would be showing a small floating translate icon next to the texts which wont break the layouts. I think magento translator does something similar.

What do you think?

PS. The reason for giving the key twice was because it is impossible to figure out what was the original key otherwise. Perhaps there could be a better way....

**Comment by vsch** [comment]
@yurtesen, I never intended the in page edit to be used extensively and did not have time to devote too much time to it. It was only intended as a quick access to translations when you see them in the page and want to quickly fix one rather than hunt for the view to find the group/key and then use the Web UI.

I agree it can be much cleaner. I opted out for re-using the Web UI method because it was already there and I did not have much time to devote to it but needed a fast way of fixing translations. If you do come up with an improved way of doing it please post a PR and I will merge it.

**Comment by yurtesen** [comment]
@vsch I am trying to do something about it actually. But it is going rather slow so far. A lot of trial/error involved. I will try to update this report once I figure it is plausable with little enough work or not :)

**Comment by yurtesen** [comment]
@vsch I tried to work on this but it is impossible to make translations inline in a way which wont break the page layout because of the way that the translations work in laravel, simply we don't know within what kind of tags etc. the translation text is. Also it would require printing translation texts without htmlentities() which is a small security risk (and unnecessary since most of the time there wont be inline translations active)

My first suggestion apparently had a drawback because it requires changes in x-editable settings etc. also it would be problematic if the key was in a tag itself such as <input text="{{ trans(key) }}"> it would be difficult to somehow embed popups to a button etc. For now, I think the simpliest way is like below:

I am thinking that since the point is to figure out the translation keys in a page quickly. I will capture the keys used in an array from trans() function at page load and then make a div in page footer with all the used keys in that page. (normally hidden) which can be made visible with a button in page and used for translating those keys.

This way there would be no need to add many custom directives to the templates. You can get away with just modifying the app.blade which gives the layout. Also, it may be possible to capture keys related to the loaded page but which are used in a function somewhere else but shown in the page later. (since trans() function will be used when rendering all the content of the page).

Unfortunately now I have few things to do before coming back to this issue. But it would be nice to hear your input. about it.

Thanks,

PS. @vsch  by the way, you could put more comments in the code :) it takes time to figure out what each block does sometimes :)

**Comment by vsch** [comment]
@yurtesen, having the keys separate from the strings in the page will be less useful because you still have to figure out which key is used where. To go to this trouble just to avoid layout changes seems like a step backwards.

You don't need to modify your page views other than using `noEditTrans()` in attributes and hidden strings where they should not contain HTML. The rest will work without modification but will cause the buttons to appear as if they have no label text with the edit link appearing beside them, at least in Chrome.

Originally I was using it that way before I had time to make changes as I recommend now.

As for comments in the code, I don't trust comments in general because they tend to fall out of sync with the code.

If you have a place where you figure out what comments would be helpful please feel free to add them and PR the changes. I will incorporate them.

**Comment by yurtesen** [comment]
@vsch I think the inconvenience is more than just broken layouts. But lets do a compromise, can we add a 2nd inline translation method? we can set in config file inline_translations=0 disabled, =1 your method =2  my method :) Below is an explanation of why people may consider my method.

1- For example many places I have to replace trans() with noEditTrans() plus add ifEditTrans() and add almost every translation string twice to page in either case. 

If I have a site with 100s of views, I would need to edit all the views. If I decide to remove translation manager, my site would become unusuable until I undo all the edits. Consider if there comes an update to laravel which is incompatible with vsch/ltm, I may be in trouble or one day you decide that you wont work on this package anymore and I need to change to another translation manager.

2- To get trans() or ifEditTrans to work, need to use either <?= or {!! to bypass htmlentitites() which may present a security risk. Normally I use {{ }} blade tags which automatically add some safety where html is not needed. (by the way those translation strings may be filled with user entered variables). I would need to use noEditTrans everywhere if I want to use {{ }}. It is a little bit cumbersome.... You are using <?= in your blade templates which is not the way they should be used. I think it is a bad example for editing the templates because it may interfere with caching of pages etc. since blade templating system would have no idea about what you are outputting -> https://laravel.com/docs/5.2/blade

3- Consider if I am forwarding a user to a page with a specific message, for example:
`redirect('/activate')->withErrors(['token' => trans('auth.invalid_token')]);`
It would be impossible to translate because actual translation key is not in view resource. However if I captured all the key names from trans() calls and make a list to be shown in the page, it would be possible to translate even this sort of texts (I think)

@vsch think about how many translations you have within a single page, 20? 30? if they were all in a popup, it would be very easy to just spot the text for a human. For example you may click on translate button and a list for a login screen would look like below and you translate in the popup:
auth.login     -> 'login'
auth.submit  -> 'submit'
auth.error    -> 'login incorrect'
...
It is not difficult to find what I want to translate, unless I have 100s of translation keys which would be rather rare I think.

I guess it  boils down to how much people want to modify their view templates. I feel uncomfortable making huge modifications to use your package ( no offense :) ) I think at least there should be a setting to select inline translation method, and you can provide both options? It could be configured in the config file to use method 1 or method 2 for inline translations? 

Thanks for your patience :)

**Comment by vsch** [comment]
@yurtesen, I won't have the time to make major changes for the next while. I am rewriting the markdown parser for my [IntelliJ/PhpStorm plugin](https://vladsch.com/product/markdown-navigator) and that is a major chunk of effort that will keep me busy for the next month, at least.

Keep in mind that design and implementation decisions were guided by minimal effort with usable results. I originally output the translation keys instead of the translations so that I could find the key. But that was cumbersome because I still had to navigate to LTM page and find the key. It evolved into outputting the link, with no logic or code modification at all. Only later did I add the rest. 

Here is my two cents worth on the subject:
1. You don't need to have an option to disable the in line translations because you already have it by not using it. i.e. do not provide a way to set inPlaceEdit() mode on you site pages.
   
   You don't need to use `ifEditTrans`, `noEditTrans` unless you want inline edits and want to make non-display translation strings available for edit.
   
   Your method would require collecting the translation keys and making them available via AJAX after the view is generated. Before the response is generated you have no way of knowing which keys are used on the page. So this would complicate the mechanism.
   
   I have no objection to this but I have no time to devote to making this work and opted out for a simple option that does the trick.
   
   I will add a mode where trans() just returns the `group.key` as if the translation is missing. That way you can get the benefit of seeing the keys, without having to make any modifications to the views.
2. You do need to enable passing through of HTML if you want to use in line edits and there is no getting around that. You can use blade `{!! !!}` or php `<?= ?>` tags for that. There is no difference because internally blade translates to php for final output. Take a look at the compiled views.
   
   The reason I used PHP instead of blade was because Laravel changed the meaning of `{{ }}` between 4.2 and 5.0 so the only way to make the views compatible with both was to use PHP.
   
   If you have user entered strings then these should be sanitized before passing them as variables to translation or you should not be using raw translation output. Security concerns make using in line edits impossible if you are passing raw user entered text as translation variables.
3. Making modifications to your views is not a requirement of this package. Whether you make these changes or not is up to you as is the decision to use the package or not. 
   
   No offence will be taken if you decide not to use the package. As none will be taken if you decide to make whatever changes you feel you need to repurpose it to your needs. If you make your idea work and feel like sharing it with others then you can generate a PR or release it as a separate package. This is the spirit, intention and benefit of open source.

I did not document inline edits for exactly the reasons you brought up and did not feel like spending more time on this functionality. As for Laravel becoming incompatible that is a major possibility. Laravel is constantly evolving and breaking compatibility. That is another reason not to incorporate inline edit into your pages unless you know what you are doing.

**Comment by yurtesen** [comment]
@vsch I dont want to take more time of yours. I think I will simply try to do something if I find time this week and return back to you. I think there is little bit misunderstanding about how the implementation will be functioning. I think my idea wont require so much effort so I can take the risk and waste little time. It is just fine if you dont accept it into your code. I will update the issue if I ever get around to do something :)

**Comment by yurtesen** [comment]
![translate](https://cloud.githubusercontent.com/assets/1926599/15800458/f7150766-2a82-11e6-8998-1bdb11e08917.gif)

This was what I meant. This only requires 1 line in app.blade.php and you can leave all the other views as they were before. It automatically detects translations used when rendering the page and makes a list, and you can still translate directly without finding the keys again from the other interface. Also it is controlled by a key in config file so your original method can keep on working.

I think it looks so much cleaner. There is not much code involved. I think I can perhaps put diffs to this issue for your review?

**Comment by vsch** [comment]
@yurtesen, that is an awesome implementation. I love it. Great work.

If you make it available I will add it to the next release.

**Comment by yurtesen** [comment]
[vsch.txt](https://github.com/vsch/laravel-translation-manager/files/299419/vsch.txt)

I made a patch against your github sources. You should be able to apply it.
Please review it first. Because it works for me but you know your code better :)

I edited your master blade template also so you can see how it works immediately.
Sorry that it took a while, I was struggling with css code :(

Let me know if you have any problems....

**Comment by yurtesen** [comment]
Here is another view where there are many more translation keys:
![translate2](https://cloud.githubusercontent.com/assets/1926599/15803160/c5bf1250-2ad8-11e6-9d4d-b51ca53695a2.gif)
By the way, I used the icons from font-awesome because default laravel template also uses them. You may change them if you like.
PS. I just realized when watching the animation that, there was a bug which showed same key twice :) I fixed it in the patch above and updated the patch file already.

**Comment by yurtesen** [comment]
@vsch when will you make a new release with this feature? It has been a month since last release...

**Comment by vsch** [comment]
@yurtesen, If you could post a pull request then anyone interested in this feature would be able to use your changes ahead of the release.

I can't wait to get a chance to play with the new in-place edit feature that you added. You did a great job unfortunately, my time is committed for the next while on another project. I will make a release as soon as I have a break in my schedule.

**Comment by yurtesen** [comment]
You are right, I should have done it from the beginning. I have made a pull request now
https://github.com/vsch/laravel-translation-manager/pull/43
