### ISSUE TITLE
Update wiki to include animated gif for new translation method.

### ISSUE THREAD

**Issue by yurtesen** [vsch/laravel-translation-manager#49]
You could use the animated gif I prepared in my previous issue:
https://github.com/vsch/laravel-translation-manager/issues/38
Here is the direct link:
https://cloud.githubusercontent.com/assets/1926599/15800458/f7150766-2a82-11e6-8998-1bdb11e08917.gif

Also I didn't quite understand the bottom notice. When I have {!! getEditableLinks() !!} down int he app.blade.php it seems to catch all the used translations ?

**Comment by vsch** [comment]
@yurtesen, the description is in the Wiki [Enabling Edit In Place On Site Pages](https://github.com/vsch/laravel-translation-manager/wiki/Enabling-Edit-In-Place-On-Site-Pages#enabling-layout-non-modifying-in-place-edit)
1. GIF added to the wiki. Thank you.
2. I split the `getEditableLinks()` into two functions so that the button could be included in a toolbar. The original function is there for backward compatibility and convenience.
   
   > **4.** You will need to add the contents of the hidden `div` to your master layout via a call
   > to a global helper function `getEditableLinks()` which includes both the button to display
   > the hidden `div` and the `div` with the links.
   > 
   >    Alternately, you can place the button separately from the links via the
   >    `getEditableTranslationsButton()` and `getEditableLinksOnly()` if you require the placement
   >    of the toggle button separately.
   > 
   >    `getEditableTranslationsButton()` can take an optional string parameter to add to the
   >    attributes of the `i` tag used to create the button. If null or not provided then
   >    `style="position: fixed; right: 5px; top: 5px; z-index:99999;"` will be used.
   > 
   >    The `getEditableTranslationsButton()` function is a convenience you can use anything that
   >    works for you by following the code of this function as an example.
