### ISSUE TITLE
After publish file takes another array format

### ISSUE THREAD

**Issue by johannebert** [vsch/laravel-translation-manager#86]
I mean i have in files lines like so:
```
    'account.user' => '/user',
    'account.user.step.two' => '/user-step-2',
    'account.user.step.three' => '/user-step-3',
```
In DB all lines are stored.
But after publish it the file looks like:
```
   'account' => [
        'user' => [
            'step' => [
                'two' => '/user-step-2',
                'three' => '/user-step-3'
            ]
        ]
    ],
```
And in this time my first line goes lost. Is there any config that do the thing and export/publish key-value from DB in another format? #

**Comment by vsch** [comment]
@Johann-Mike, in the DB all keys are stored because the dot separated keys are stored as a full path. On export dot separated keys are assumed to be array paths so the value assigned to the array is the array and not the translation value.

Dot separator by convention is used to represent arrays.

I will take a look at the code to see if implementing suppression of array path expansion if the root path has a value assigned can be a solution to your use case.

**Comment by johannebert** [comment]
@vsch thanks for your reply and looking for a solution.

But I think it is more my issue, because i didn't follow the right way of dot separated key - value array. Now i checked and changed my files to right structure of array and it is looks good.
So this thread can be closed ;)

**Comment by vsch** [comment]
@Johann-Mike, I agree that it is an issue in not following the dot convention but LTM should at least notify users when this occurs but ideally it should result in the same result as was imported. Otherwise it causes unexpected "quirks" that look like errors.

**Comment by vsch** [comment]
@Johann-Mike, I added an error message to the next release when an export causes a translation value to be lost because there are keys that create child values.

Here is an example of export for your sample:

![image](https://cloud.githubusercontent.com/assets/10299086/25895597/8dbb1878-354e-11e7-9e03-82c76abe923b.png)

Trying to preserve incorrect dot usage would require writing custom handling of array dot functions instead of using Laravel provided functions.

**Comment by johannebert** [comment]
@vsch thank you. 

What was also missing in LTM config for me is:
`'use_cookies' => false,`

Because i switch often the locale and it causes problems with translations of trans() with used cookies.

**Comment by gerardreches** [comment]
@vsch I'm in the same problem right now.

I have some translations for routes. One of these routes (`/services`) is for a services page, so I called the string `routes.services`. The thing is that the services page is a top level for the different services:

`/services/testimonials`
`/services/transactions`
`/services/estate`
and more... So the strings are `routes.services.testimonials`, `routes.services.transactions`, `routes.services.estate`, and so on.

When I publish the `routes` group, it shows me
>Incorrect use of dot convention for translation keys (value will be overwritten with an array of child values):
>     routes::
>          services

and my laravel project shows a `trim()` error until I delete the generated translations.

I know that this is logic, because there are two equal keys with different values: one contains a string, and the other contains an array.

Is there some workaround for this? Or the only option is to rename the `routes.services` key?

**Comment by vsch** [comment]
@gerardreches, the dot notation by convention is used to separate arrays. The issue is that on publishing the dot convention is always interpreted as array convention. The code to ignore the array convention when a key has a value assigned that would be overwritten by an array gets to be convoluted.

Would it be possible for you to use another delimiter than a period `.` so it does not conflict with the translation array notation, for example a dash `-` would do the trick.
